name: Build Heltec V3/V4 Binaries

on:
  workflow_dispatch:

permissions: read-all

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Get release version string
        run: |
          echo "long=$(./bin/buildinfo.py long)" >> $GITHUB_OUTPUT
        id: version
        env:
          BUILD_LOCATION: local
    outputs:
      long: ${{ steps.version.outputs.long }}

  build:
    needs: [version]
    strategy:
      fail-fast: false
      matrix:
        target:
          - heltec-v3
          - heltec-v4
    uses: ./.github/workflows/build_firmware.yml
    with:
      version: ${{ needs.version.outputs.long }}
      pio_env: ${{ matrix.target }}
      platform: esp32s3

  gather-artifacts:
    runs-on: ubuntu-latest
    needs: [version, build]
    steps:
      - uses: actions/download-artifact@v7
        with:
          pattern: firmware-esp32s3-*-${{ needs.version.outputs.long }}
          merge-multiple: true
          path: ./output

      - name: Show downloaded artifacts
        run: ls -lR ./output

      - name: Upload Heltec bin files
        uses: actions/upload-artifact@v6
        with:
          name: heltec-v3-v4-bins-${{ needs.version.outputs.long }}
          overwrite: true
          path: |
            ./output/**/*.bin
